### ISSUE TITLE
Add exporting models to Azure and AWS with a single line of code to Deep_AutoViML

### ISSUE THREAD

**Issue by trumboosahil** [AutoViML/deep_autoviml#13]

**Comment by AutoViML** [comment]
Hi @trumboosahil 👍 
Any updates? Do you still want to do this?
AutoViML

**Comment by trumboosahil** [comment]
Yes, I was  busy some personal things,

Can you suggest how you are anticipating it to be implemented.

**Comment by AutoViML** [comment]
Can you please check other tools such as PyCaret and see how they have implementing exporting models to AWS, Azure etc. I don't know how. That's why I am asking for help here.
