### ISSUE TITLE
Adding conda install option

### ISSUE THREAD

**Issue by sugatoray** [AutoViML/deep_autoviml#14]
Add `deep_autoviml` to conda-forge channel.

**Comment by sugatoray** [comment]
I have started working on a conda-forge PR to add deep_autoviml to conda-forge. https://github.com/conda-forge/staged-recipes/pull/17544

**Comment by sugatoray** [comment]
`tensorflow-text ==2.5.0` is a dependency of `deep_autoviml`. The problem is that there is no source file for `tensorflow-text`: *it's all wheels (binary files)*. 

![image](https://user-images.githubusercontent.com/10201242/149589905-f69b5253-5906-4fb3-b871-fcf4260224bf.png)

**Comment by sugatoray** [comment]
A possible solution could be: add `tensorflow-text` to optional dependencies 

```python
# setup.py

setup(
	...
	extras_require={
		"text": ["tensorflow-text>=2.5.0",],
	}
)
```

### References

- https://github.com/RasaHQ/whatlies/blob/main/setup.py

**Comment by sugatoray** [comment]
This would require removal of any occurrences of `tensorflow_text` from `deep_autoviml.__init__.py`.

![image](https://user-images.githubusercontent.com/10201242/149603509-ac27f0a4-feea-4451-a513-7af5344a22ff.png)

Ref: https://github.com/AutoViML/deep_autoviml/search?q=tensorflow_text

**Comment by AutoViML** [comment]
Dear @sugatoray 👍 
Thank you so much for the help in making this library available via conda-forge.

I would love to make the changes you suggested. But if you want - you can make a pull request for all these files so I can merge the request and you would show up as a contributor. Would you want to do that?

AutoViML

**Comment by sugatoray** [comment]
Could you please tell me which function in `__init__.py` depends on `tensorflow_text`?

**Comment by AutoViML** [comment]
Actually nothing specifically but it is needed whenever you deal with TF functions.

Please also make sure that the specific version of tensorflow text as in here:
```
extras_require={
		"text": ["tensorflow-text==2.5.1",],
```
Thanks
AutoViML

**Comment by AutoViML** [comment]
Hi @sugatoray 👍 
I have made the changes suggested by you and updated the GitHub.
Can you please let me know if this helps,
Thanks,

AutoViML

**Comment by sugatoray** [comment]
Thank you. Please also test if you import the library with these changes, if everything works as expected. Once, you think it is ready please consider using a version string like `0.0.78.dev1`. This will ensure this shows up as a pre-release on PyPI and when you release `v0.0.78`, it will come after these pre-releases.

**Comment by AutoViML** [comment]
Ok great I will do that. Thanks a lot for these suggestions.

**Comment by sugatoray** [comment]
One more thing: if you have not used [testpypy](https://test.pypi.org/) yet, please consider using it for releasing the package on a test basis. This helps you keep your PyPI releases clear of erroneous uploads.

- https://packaging.python.org/en/latest/guides/using-testpypi/#using-testpypi-with-twine

I often test uploading packages to testpypi first. It helps spot any avoidable errors.

**Comment by AutoViML** [comment]
So I made the changes and it works as expected in Colab. I have pushed the changes as pre-release dev1 as you have suggested. Please see if this works in the conda-forge process.
Thanks again!

**Comment by sugatoray** [comment]
Great! Let me see and get back to you later.

Is it uploaded to pypi? I don't see any newer versions yet.

**Comment by AutoViML** [comment]
I Uploaded to PyPi. It's done.

**Comment by AutoViML** [comment]
Hi @sugatoray 👍 
Are there any more changes to be done?

**Comment by TomLucidor** [comment]
@sugatoray your exact problem about `tensorflow-text` (in windows) is exactly why `AutoKeras` fails to install as well.

As for @AutoViML Current version of tensorflow is somewhere between `2.16.1` and `2.18.0` (for Python 3.12), out of range since it needs Python 3.11 or blow atm?
