### ISSUE TITLE
Need a clarification on AutoViML

### ISSUE THREAD

**Issue by Rohith616** [AutoViML/deep_autoviml#17]
Hi i am currently doing a research on Automated ML, i went through Auto-TS it is really good , but i have a doubt can we use AutoViML for time series will it preform well. 

it will be helpful if i get an expert opinion.
Thank you.

**Comment by AutoViML** [comment]
Hi @Rohithtechis 👍 
I believe AutoViML will perform well on time series problems. It is pretty comparable to Auto_TS in the ML part. However, Auto_TS has other algorithms which you can try such as FB Prophet, ARIMA, SARIMAX, etc.

**Comment by Rohith616** [comment]
Thank you
