### ISSUE TITLE
Option to disable EDA

### ISSUE THREAD

**Issue by ghost** [AutoViML/deep_autoviml#19]
In order to generate baseline results, it would be useful if we could disable Exploratory Data Analysis.

**Comment by AutoViML** [comment]
Hi @Fractal-Anaphora 
Thank you for trying out Deep AutoViML 👍 

At the moment there is no option to disable EDA. If you can try sampling your data with a smaller dataset and trying it first, then you may be able to overcome the hardware limitations.
Let me know.
Thanks
AutoViML
