### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by jbrepogmailcom** [AutoViML/deep_autoviml#21]
Hello. Beside cyclic dependency problem with installation via pip, I also have the error in subject in code taken from examples:

from deep_autoviml import deep_autoviml as deepauto
model = deepauto(df, target=target, feateng_cols=features)

How to proceed?

Same error in python3.8 and in 3.7

**Comment by AutoViML** [comment]
Hello Your syntax for deepauto is incrrect. There seems  to be an extra argument 'featng_cols' below which is not mentioned in my README.That could be the reason. Please read the README or look at the examples notebooks I have provided in the Examples folder.

model = deepauto(df, target=target, feateng_cols=features)
Auto Vimal
    On Friday, April 21, 2023 at 09:32:23 AM EDT, jaybee ***@***.***> wrote:  
 
 


Hello. Beside cyclic dependency problem with installation via pip, I also have the error in subject in code taken from examples:

from deep_autoviml import deep_autoviml as deepauto
model = deepauto(df, target=target, feateng_cols=features)

How to proceed?
