### ISSUE TITLE
unable to install deep_autoviml

### ISSUE THREAD

**Issue by GDGauravDutta** [AutoViML/deep_autoviml#23]
Collecting deep_autoviml
  Downloading deep_autoviml-0.0.84-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: emoji in /opt/conda/lib/python3.10/site-packages (from deep_autoviml) (2.11.0)
Requirement already satisfied: ipython in /opt/conda/lib/python3.10/site-packages (from deep_autoviml) (8.20.0)
Collecting jupyter (from deep_autoviml)
  Downloading jupyter-1.0.0-py2.py3-none-any.whl.metadata (995 bytes)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (from deep_autoviml) (3.7.5)
Collecting numpy~=1.19.2 (from deep_autoviml)
  Downloading numpy-1.19.5.zip (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 47.7 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: optuna in /opt/conda/lib/python3.10/site-packages (from deep_autoviml) (3.6.1)
Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (from deep_autoviml) (2.2.2)
Requirement already satisfied: regex in /opt/conda/lib/python3.10/site-packages (from deep_autoviml) (2023.12.25)
Collecting scikit-learn<=0.24.2,>=0.23.1 (from deep_autoviml)
  Downloading scikit-learn-0.24.2.tar.gz (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 86.0 MB/s eta 0:00:00:00:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1613 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      <string>:116: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
      INFO: C compiler: gcc -pthread -B /opt/conda/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/include -fPIC -O2 -isystem /opt/conda/include -fPIC
      
     
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by AutoViML** [comment]
Hi @GDGauravDutta 
thanks for trying out deep_autoviml in Kaggle 👍 

I have updated the setup.py and requirements.txt files and have tested it on Kaggle. It installs correctly (see screenshot)
![image](https://github.com/AutoViML/deep_autoviml/assets/51647480/c79f33f2-bf01-4694-b1ab-4fb0c16a4e7c)

Please upgrade to the latest version and continue.
Kaggle Notebook: https://www.kaggle.com/code/rsesha/deep-autoviml-on-flood-prediction
Auto Vimal

**Comment by GDGauravDutta** [comment]
Working now
