### ISSUE TITLE
Seems too memory intensive?

### ISSUE THREAD

**Issue by jimmyland22** [AutoViML/deep_autoviml#3]
I'm trying to follow the tutorials to try image and NLP classification. On Colab, the runtime keeps crashing due to running out of memory, so I moved it into my local machine. 
On a sample Kaggle NLP dataset, I'm getting this message

MemoryError: Unable to allocate 72.6 GiB for an array with shape (18679895,) and data type <U1043

Seems like quite a demand. The data I'm trying to use is
https://www.kaggle.com/clmentbisaillon/fake-and-real-news-dataset

**Comment by AutoViML** [comment]
Hi @jimmyland22 👍 

As you have rightly pointed out, there was a bug in the code. I have fixed it and now you can see how good the results are on your fake news classification dataset here:

[fake_news_classification_notebook](https://www.kaggle.com/rsesha/fake-news-classification-deep-autoviml-100)

Please upgrade to the latest version and re-run your notebook again and it should work.
