### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by jocelynbaduria** [AutoViML/deep_autoviml#5]
Following the tutorial for Image Classification, I am getting below error

![Screen Shot 2021-10-30 at 12 05 15 AM](https://user-images.githubusercontent.com/62075076/139523882-a4bab592-b3aa-4de2-b771-a86c4bc8cf75.png)

My dataset:
https://drive.google.com/drive/folders/1sQpk94eAhq4ADBHpCh3yc2D4YbJxBpCn?usp=sharing

**Comment by AutoViML** [comment]
Hi @jocelynbaduria 👍 
I believe that deep_autoviml cannot access Google drives as far as I know.

You will have to run it locally on your local machine or on Kaggle Notebooks.

Currently there is no way to authenticate and access Google drives.

Hope this helps.
