### ISSUE TITLE
test_size should be either positive and smaller than the number of samples

### ISSUE THREAD

**Issue by miggytrinidad** [AutoViML/deep_autoviml#6]
I am having an error in training a model, it says:

test_size=-22.10536044362292 should be either positive and smaller than the number of samples 4328 or a float in the (0, 1) range

**Comment by AutoViML** [comment]
Hi @miggytrinidad 👍 
Thank you for testing out deep_autoviml. Can you check if you have the latest version (0.0.71)?
The reason I ask is that I just fixed it and it was uploaded to the latest version. If you don't have the latest version, please upgrade using:
`pip install deep_autoviml --upgrade`

If you have the latest version and still getting this error, please let me know and I will investigate it. Can you paste a link to tyhe notebook or dataset that you are using to get that error??

Thanks
AutoViML

**Comment by hunaidkhan2000** [comment]
> I am having an error in training a model, it says:
> 
> test_size=-22.10536044362292 should be either positive and smaller than the number of samples 4328 or a float in the (0, 1) range

I am also getting the same error with test_size=-5.25

**Comment by AutoViML** [comment]
Hi @miggytrinidad @hunaidkhan2000 
Can you please try it with the latest version:

pip install deep_autoviml --upgrade

thanks
AutoViML

**Comment by miggytrinidad** [comment]
@AutoViML it's now working!
