### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by NeyoxDrago** [AutoViML/deep_autoviml#7]
if we pass only the text column in the deep_autoViML , then i am getting this error.

ValueError: not enough values to unpack (expected 2, got 0)

any clues ?

**Comment by AutoViML** [comment]
Hi @NeyoxDrago 👍 
It is hard to tell unless you paste a screenshot of the error fully or the data snippet of how it looks. Sorry
AutoViML
