### ISSUE TITLE
Feature: Support for Seq2Seq (LSTM) model for next word prediction 

### ISSUE THREAD

**Issue by chekoduadarsh** [AutoViML/deep_autoviml#8]
## Issue

I would like to take up the task to implement Seq2Seq models on deep_AutoViML. This will allow this library to perform operations like next word prediction, Text summarization etc. 

## Proposed approach

```python3

keras_model_type = "next_word_prediction" 
deepauto.fit(train_datafile, target, keras_model_type=keras_model_type,
		project_name=project_name, keras_options=keras_options, model_options=model_options, 
		save_model_flag=False, verbose=1)

```

We can use `keras_model_type` in deep_autoviml.py to check for the string `next word prediction`, here the data will be preprocessed and an appropriate model will be chosen. After this chosen model will be trained for the given data. Users can either enter or use the default early stopping, epochs and other features.

```python3
if keras_model_type.lower() in ['image', 'images', "image_classification"]:
   # Train Image classification

elif keras_model_type.lower() in ['text classification', "text_classification"]:
   # Train for Text classification

elif keras_model_type.lower() in ['next word prediction', "next_word_prediction"]:
   # Train for next word prediction

```

Similarly, We can create a model for time series prediction.

@AutoViML: If you have a better approach to solving this problem let me know

**Comment by AutoViML** [comment]
Hi @chekoduadarsh 👍 
I have added you as a collaborator to this repository - once you accept the invite I will be able to assign a project I have created in this repo. You can see it here.
https://github.com/users/AutoViML/projects/2/views/1

**Comment by chekoduadarsh** [comment]
@AutoViML  Thank you, I have accepted your offer Soon I will make PR request on the above feature. Thank you for this opportunity.

**Comment by AutoViML** [comment]
Hi @chekoduadarsh 👍 
Any updates?
AutoViML

**Comment by chekoduadarsh** [comment]
Hello @AutoViML ,

Sorry for the delayed response.
*(I was busy with medical and personal things)*

please have a look into the forked repository https://github.com/chekoduadarsh/deep_autoviml

## Timeseries prediction -> Status update

I have implemented LSTM, GRU and RNN Models for time series prediction and I have tested it with [energydata_complete](https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv) from https://archive.ics.uci.edu

- [x] Make LSTM, GRU and RNN Models
- [x] Use TimeseriesGenerator and parse test/train data
- [x] Successfully train a model and make a example notebook 
- [x] Comment the code and mention the source 

*ref: https://github.com/srivatsan88/End-to-End-Time-Series/blob/master/Multivariate_Time_Series_Modeling_using_LSTM.ipynb*
*ref: https://www.youtube.com/watch?v=i4vGKgbtf1U&list=PL3N9eeOlCrP5cK0QRQxeJd6GrQvhAtpBK&index=12*


Please review the changes and let me know if you want me to do something before i make the pull request. :pray:

Thank you
Adarsh C

**Comment by AutoViML** [comment]
Hi @chekoduadarsh 👍 
I will test the code with a few classic time series datasets and then approve. 
thanks for the quick turnaround!
AutoViML

**Comment by AutoViML** [comment]
Hi @chekoduadarsh :
can you create a Pull Request for my github??
 don't have much time and would appreciate the help,
Thanks
AutoVimal

**Comment by chekoduadarsh** [comment]
Hello @AutoViML 

I will create a PR! But I don't think the solution is complete! I am sorry but I couldn't finalize it I think

**Comment by AutoViML** [comment]
Ok let me see if I can work on it. Closing this for now.
Thank you for all your help.
Auto Vimal
